events {}
http {
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;

    upstream ingestion_service {
        server ingestion-service:3000;
    }

    upstream alert_service {
        server alert-service:3001;
    }

    server {
        listen 80;

        location /api/ingest/ {
            limit_req zone=api_limit burst=10 nodelay;
            proxy_pass http://ingestion_service/api/ingest/;
        }

        location /api/alerts {
            limit_req zone=api_limit burst=10 nodelay;
            proxy_pass http://alert_service/api/alerts;
        }

        location /health {
            return 200 'Solar Shield Gateway OK';
        }
    }
}
